chime-experiment/chimedb

chimedb/core/__init__.py, chimedb/core/orm.py
This avoids the following, which happens if an uninstalled chimedb
package is in the import path:
```
bash$ python
>>> import chimedb.core
>>> chimedb.core.orm.create_tables()
usage:  [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
or:  --help [cmd1 cmd2 ...]
or:  --help-commands
or:  cmd --help
error: no commands supplied
bash$
```
which is the result of this function trying to import the `setup.py` it
finds in the base `chimedb` directory.  (Note the exit-to-shell).
We fix this by explicitly avoiding the import of `chimedb.setup`.
Since the infrastructure is there, I've also explicitly disabled the
import of chimedb.core, whose tables are already in scope, and
chimedb.config, which shouldn't ever define tables to create
Both an additional bell and an additional whistle have been …
=> fix(create_tables): Don't try to import chimedb.setup

.travis.yml, chimedb/core/__init__.py, chimedb/core/connectdb.py, chimedb/core/orm.py, test/test_current_connector.py, test/test_sqlite.py
Also added some rudiementary tests, but mostly sqlite based at the moment.
To get the test to be able to run read-only tests, extended the
SqliteConnector to handle both read-only requests and also Sqlite URIs
in general.
Also simplified the RC file format to avoid unnecessary duplication of
connection data.
=> fix(connectdb): fix switching between ro and rw connectors

README.md, chimedb/core/__init__.py, chimedb/core/connectdb.py, test/test_test_enable.py
This adds a function, `chimedb.core.test_enable()` which turns on "test-safe mode" which should prevent running unit tests against the production database.
=> feat(core): test-safe mode

chimedb/core/connectdb.py, test/test_test_enable.py
If CHIMEDB_TEST_ENABLE is present in the environment (and not the
empty value), test-safe mode will be turned on when connect() is called.
=> feat(connectdb): turn on test-safe mode via environment

chimedb/core/__init__.py, chimedb/core/connectdb.py, chimedb/core/context.py, test/test_decorator.py, test/test_sqlite.py
Because I hate me some race conditions, after realising that `cdf` (and hence the node hardware tracker I'm writing) could run in to trouble by independently accessing the database first in a parameter callback and then, separately, in a command callback, I figured someone should fix it.
So here we go: this adds a decorator (`@atomic`) we can use to transactionify a click command:
```(Python)
import click
import chimedb.core as db
@db.atomic(read_write=True)
@click.group
@click.option("--opt", type=SOMETHING_INVOLVING_CHIMEDB_ACCESS)
def whatever(opt):
more_chimedb_access_here()
```
The database connection happens automatically.  The transaction will automatically be committed when the command finishes, unless it raises an exception, which will cause the whole thing to be rolled back (per …
=> feat(core): add atomic decorator/context manager

README.md
Part of this: https://github.com/chime-experiment/Pipeline/issues/92
=> docs: chimedb is public and should be installed via https

chimedb/core/connectdb.py
This avoids instantiating a new peewee `Database` (and, hence, creating a new database connection) in the `get_peewee_database` calls if one already exists.  I suspect this is what we intended to happen all along.
Without this fix, every call to `chimedb.core.connect()` results in a new connection to the database being established.  In theory, for normal connections to the MySQL database, this is not a problem: one connection should be the same as any other.  (The previous connection is closed during GC).
However, this can cause trouble when using an in-memory SQLite database in test-safe mode.
I also wonder if this is the cause of some of the unexplained DB connection loss we've experienced, especially in `alpenhornd`, but I have no real evidence for that.
=> fix(connectdb): Re-use existing DB connection

setup.py
Apparently `is_connection_usable` was added in Peewee 3.12.
=> build: Bump peewee version requirement

chimedb/core/connectdb.py, chimedb/core/context.py, chimedb/core/exceptions.py, chimedb/core/orm.py, setup.py
- refactor: use pure python connector that doesn't require mysql libraries
- refactor: remove Python 2 patches
=> Pure Python connector to remove MySQL binary dep

setup.py
Newer versions of mysql-connector seem to have an issue with the charset settings that old versions of MariaDB use, this restricts the version to ones that I know work.
=> fix: restrict the version of mysql-connector to one that works with MariaDB

chimedb/core/alpenhorn.py, chimedb/core/connectdb.py, chimedb/core/orm.py
This PR adds an alpenhorn2-style database extension module called `chimedb.core.alpenhorn`.
An alpenhorn-2 extension needs to provide a `register_extension()` function.  In the case of a database extension, like this one, the `register_extension` function returns a dictionary containing a `"database"` key whose value is a sub-dictionary describing the capabilities of the registered extension.
In particular, the CHIMEDB database extension provides access to the standard CHIMEDB `connect` and `close` methods for managing database connections.  All connections provided to alpenhorn have `read_write=True`.
This PR is tied to https://github.com/radiocosmology/alpenhorn/pull/144, which modifies alpenhorn to support the type of `register_extension` we provide.
This PR also fixes `EnumField` and …
=> Alpenhorn-2 integration

chimedb/core/connectdb.py
Disable DEBUG messages while calling mysql.connector.connect because it leaks the DB password to the log at that level.
Closes #35
=> fix(connectdb): Don't leak password to log

setup.py
This fixes a regression from PR #27 which replaced the `MySQLdb` requirement with `mysql.connector`.  This substitution effectively removed support for MySQL from `peewee` in new installs, because `peewee` was using `MySQLdb` for MySQL database access, but it doesn't have `MySQLdb` as a dependency (because it doesn't want to force MySQL on you if you don't want it).
To fix this, I've added a requirement for `pymsql`, a pure-python replacement for `MySQLdb` which `peewee` supports as an alternative.
=> build: Add pymysql dependency

chimedb/core/mediawiki.py
The field in the database is a VARBINARY.  Using pewee's `TextField` on that returns values as `"bytearray(b'Name')"` (i.e. as a Python `str` containing the `repr` of the `binary` field data, which is just wild).
Changing the field type to `BlobField` results in `MediaWikiUser.user_name` being a `binary`-encoded string, as expected.
Closes #31
=> fix(mediawiki): Fix field type of MediaWikiUser.user_name

chimedb/core/connectdb.py, setup.py
Three things:
1. Upgrade the minimum peewee version to 3.16.3 to avoid needing `pymsql`.  Closes #39 
2. Be less draconian about filtering passwords from the log.  Now only the actual password message is filtered, and the filter can be stopped by calling connectdb.secure_logging(False).
3. Fix the deprecation warning in execute_sql() for peewee >= 3.16, which outputs a DeprecationWarning in execute_sql if `commit` (which is now unused) is not None.
=> fix(connectdb): Upgrade to peewee-3.16.3

.github/workflows/main.yml, chimedb/core/__init__.py, chimedb/core/context.py, setup.py, test/test_current_connector.py, test/test_decorator.py, test/test_sqlite.py, test/test_test_enable.py
* Ruff check
* Minimum python set to 3.9.
* Test on both 3.9 and 3.12
* Renamed the test DB table in the test suite to "TableTest" to avoid confusing pytest.
=> ci: Add ruff check and update workflows

chimedb/core/__init__.py, pyproject.toml
My bad.
This project is supposed to advertise that it is the base `chimedb` package.   Which explains all the `chimedb @ ...` requirements elsewhere.
=> Project name is 'chimedb' not 'chimedb.core'

chimedb/core/alpenhorn.py, chimedb/core/connectdb.py, chimedb/core/orm.py
This ensure all chimedb tables are connected to the database, not just alpenhorn's own.
Also a lot of futzing with error messages to try to propagage CHIMEdb connection problems all the way out to the alpenhorn CLI, when appropriate.
=> fix(alpenhorn): Use connect_database for database connection

pyproject.toml
There's a bug with peewee and the version format returned by `mysql-connector`. For now, just pin the version.
=> fix(pyproject): pin max version of mysql_connector

chimedb/core/connectdb.py, pyproject.toml
Originally, `chimedb.core` used the C-extension `MySQLdb` to connect to the database.  Eventually we got fed up with having to compile against the mysql client CAPI library, so we switched to `mysql.connector`, which was a new pure-python alternative provided by Oracle (owners of MySQL).
However, that was all back in the Python2 times.  Now there's `pymysql` which is `peewee`'s preferred way of interfacing with MySQL.  So, let's try that.
This is mostly a drop-in replacement, but it does allow us to do away with both the `mysql.connector` log filtering (which was printing the DB password in plain text at log level DEBUG) and also the `playhouse.mysql_ext` stub providing `MySQLDatabase` support for `mysql.connector` (which is where the 9.3.0 bug we've encountered comes from).
I've done …
=> refactor(connectdb): Use pymysql instead of mysql.connector
